const express = require('express')
const userSignUpController = require('../controllers/userSignup')
const userSignInController = require('../controllers/userLogin')
const userDetailsController = require('../controllers/userDetails')
const authToken = require('../middleware/authToken')
const userLogOut = require('../controllers/userLogOut')
const allUsers = require('../controllers/allUsers')
const updateUser = require('../controllers/updateUser')
const router = express.Router()
router.post('/signup', userSignUpController)
router.post('/login', userSignInController)
router.get('/userdetails',authToken, userDetailsController)
router.get('/userlogout', userLogOut)
router.get('/all-users',authToken ,allUsers)
router.post('/update-user',authToken, updateUser)
module.exports = router